#!/usr/bin/env bash
set -euo pipefail

# AUTOGENERATED by: /home/jaeden/.config/rofi/scripts/switch-launcher-layout.sh
# Selected launcher: type-2 / style-2

dir="$HOME/.config/rofi/layouts/launchers/type-2"
theme="style-2"

exec rofi -show drun -theme "${dir}/${theme}.rasi"
