#!/usr/bin/env bash
set -euo pipefail

ROFI_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/rofi"
LAUNCHER_LAYOUTS="$ROFI_DIR/layouts/launchers"
TARGET="$ROFI_DIR/scripts/launcher.sh"

command -v rofi >/dev/null 2>&1 || { echo "rofi not found in PATH" >&2; exit 1; }

[[ -d "$LAUNCHER_LAYOUTS" ]] || { echo "Missing launcher layouts dir: $LAUNCHER_LAYOUTS" >&2; exit 1; }
mkdir -p "$ROFI_DIR/scripts"

# If stow created this as a symlink, remove it so we can own it locally
if [[ -L "$TARGET" ]]; then
  rm -f "$TARGET"
fi

# Pick launcher type (folder under layouts/launchers/)
type="$(
  find -L "$LAUNCHER_LAYOUTS" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' \
    | sort \
    | rofi -dmenu -i -p "Launcher type"
)"
[[ -z "${type:-}" ]] && exit 0

type_dir="$LAUNCHER_LAYOUTS/$type"
[[ -d "$type_dir" ]] || { echo "Type not found: $type_dir" >&2; exit 1; }

# Pick style (style-*.rasi within selected type)
style_file="$(
  find -L "$type_dir" -mindepth 1 -maxdepth 1 -type f -name 'style-*.rasi' -printf '%f\n' \
    | sort -V \
    | rofi -dmenu -i -p "Style"
)"
[[ -z "${style_file:-}" ]] && exit 0

style="${style_file%.rasi}" # "style-1"

# Overwrite launcher as a REAL local file
cat > "$TARGET" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# AUTOGENERATED by: $ROFI_DIR/scripts/switch-launcher-layout.sh
# Selected launcher: $type / $style

dir="\$HOME/.config/rofi/layouts/launchers/$type"
theme="$style"

exec rofi -show drun -theme "\${dir}/\${theme}.rasi"
EOF

chmod +x "$TARGET"
