# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/



# Source all the hyprland settings
source = settings/monitor.conf
source = settings/programs.conf
source = settings/autostart.conf
source = settings/environment-variables.conf
source = settings/permissions.conf
source = settings/look-and-feel.conf
source = settings/input.conf
source = settings/keybindings.conf
source = settings/windows-and-workspaces.conf