#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Wallpaper
exec-once = swww-daemon

# Waybar
exec-once = ~/.config/waybar/bin/launch.sh

# Notification center
exec-once = swaync

# Clipboard manager

# Privilege escalation
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1