###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$refresh-waybar = ~/.config/waybar/bin/refresh.sh
$refresh-swaync = ~/.config/swaync/bin/refresh.sh
$app-launcher = ~/.config/rofi/bin/launcher.sh || pkill rofi
$rofi-control-center = ~/.config/rofi/bin/control-center/control-center.sh || pkill rofi
$wlogout = ~/.config/wlogout/bin/launch.sh || pkill wlogout
$toggle-swaync = ~/.config/swaync/bin/toggle-view.sh