###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$refresh-waybar = ~/.config/waybar/bin/launch.sh
$refresh-swaync = ~/.config/swaync/bin/launch.sh
$app-launcher = ~/.config/rofi/scripts/launcher.sh || pkill rofi
$rofi-control-center = ~/.config/rofi/scripts/control-center.sh || pkill rofi
